model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='DRCA',
        pretrained=None,
        num_frames=8,
        img_size=224,
        patch_size=16,
        embed_dims=384,
        num_heads=6,
        in_channels=3,
        comp_insert_layer=-1,
        comp_k=8,
        comp_strategy="diff_rank",
        comp_module="sal_ref",
        sigma=0.05,
        num_samples=500,
        dropout_ratio=0.0,
        transformer_layers=None,
        norm_cfg=dict(type='LN', eps=1e-06)),
    cls_head=dict(type='ClsHead', num_classes=200, in_channels=384),
    train_cfg=None,
    test_cfg=dict(average_clips='prob'))